name: Deploy to kubernetes app on AKS

on:
  push:
    branches:
      - main
    paths:
      - 'sock-shop-app/k8s/**'
      - 'sock-shop-app/monitoring/**'
      - 'sock-shop-app/alerting/**'
      - 'sock-shop-app/logging/**'

  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input'
        required: false
        default: 'default_value'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Set up Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          
      # - name: Decode and save kubeconfig
      #   run: |
      #     echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to AKS
        run: |
          cd sock-shop-app/k8s
          kubectl apply -f sock-shop-dp.yaml

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Add Helm repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

      - name: Install Prometheus
        run: |
          kubectl create namespace monitoring || true
          helm install prometheus prometheus-community/prometheus --namespace monitoring

      - name: Install Grafana
        run: |
          helm install grafana grafana/grafana --namespace monitoring

      - name: Add NGINX Ingress Controller Helm repository
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
      
      - name: Install NGINX Ingress Controller
        run: |
          helm install nginx-ingress ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --create-namespace \
            --set controller.replicaCount=2 \
            --set defaultBackend.enabled=true

      - name: Apply Ingress and Issuer
        run: |
          cd sock-shop-app/k8s
          kubectl apply -f ingress.yaml
          kubectl apply -f issuer.yaml
      
      - name: Apply Monitoring Configurations
        run: |
          cd sock-shop-app/monitoring
          kubectl apply $(ls *-prometheus-*.yaml | awk ' { print " -f " $1 } ')
          kubectl apply $(ls *-grafana-*.yaml | awk ' { print " -f " $1 }'  | grep -v grafana-import)
      
      - name: Apply Alerting Configurations
        run: |
          cd sock-shop-app/alerting
          kubectl apply $(ls *.yaml | awk '{print " -f " $1}')
      
      - name: Apply Logging Configurations
        run: |
          cd sock-shop-app/logging
          kubectl apply $(ls *.yaml | awk '{print " -f " $1}')

